services:
    garant_file_preview_generator.remote_client:
        class: Garant\FilePreviewGeneratorBundle\Client\RemoteClient
        calls:
            - [setContainer, ["@service_container"]]

    garant_file_preview_generator.libreoffice_generator:
        class: Garant\FilePreviewGeneratorBundle\Generator\LibreOfficeGenerator

    garant_file_preview_generator.msoffice_generator:
          class: Garant\FilePreviewGeneratorBundle\Generator\MSOfficeGenerator