parameters:
    garant_file_preview_generator.remote_client.connect_timeout: 5
    garant_file_preview_generator.remote_client.class: Garant\FilePreviewGeneratorBundle\Client\RemoteClient
    garant_file_preview_generator.binary.loader.filesystem_class: Garant\FilePreviewGeneratorBundle\Binary\Loader\FileSystemLoader
    garant_file_preview_generator.generator_factory.class: Garant\FilePreviewGeneratorBundle\Generator\Factory\GeneratorFactory
    garant_file_preview_generator.libreoffice_generator.class: Garant\FilePreviewGeneratorBundle\Generator\LibreOfficeGenerator
    garant_file_preview_generator.msword_generator.class: Garant\FilePreviewGeneratorBundle\Generator\MSWordGenerator
    garant_file_preview_generator.msexcel_generator.class: Garant\FilePreviewGeneratorBundle\Generator\MSExcelGenerator
    garant_file_preview_generator.powerpoint_generator.class: Garant\FilePreviewGeneratorBundle\Generator\MSPowerPointGenerator
    garant_file_preview_generator.image_to_image_generator.class: Garant\FilePreviewGeneratorBundle\Generator\ImageToImageGenerator
    garant_file_preview_generator.image_to_pdf_generator.class: Garant\FilePreviewGeneratorBundle\Generator\ImageToPDFGenerator
    garant_file_preview_generator.pdf_to_image_generator.class: Garant\FilePreviewGeneratorBundle\Generator\PDFToImageGenerator
    garant_file_preview_generator.supervisor_class: Garant\FilePreviewGeneratorBundle\Supervisor\Supervisor

services:
    garant_file_preview_generator.binary.loader.filesystem:
        class: '%garant_file_preview_generator.binary.loader.filesystem_class%'
        #@todo Fix the third argument
        arguments: ['@liip_imagine.mime_type_guesser', '@liip_imagine.extension_guesser', '%kernel.root_dir%/../web', '@liip_imagine.binary.locator.filesystem']

    garant_file_preview_generator.remote_client:
        class: '%garant_file_preview_generator.remote_client.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setContainer, ["@service_container"]]

    garant_file_preview_generator.generator_factory:
        class: '%garant_file_preview_generator.generator_factory.class%'

    garant_file_preview_generator.libreoffice_generator:
        class: '%garant_file_preview_generator.libreoffice_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.msword_generator:
        class: '%garant_file_preview_generator.msword_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.msexcel_generator:
        class: '%garant_file_preview_generator.msexcel_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.powerpoint_generator:
        class: '%garant_file_preview_generator.powerpoint_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.image_to_image_generator:
        class: '%garant_file_preview_generator.image_to_image_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.image_to_pdf_generator:
        class: '%garant_file_preview_generator.image_to_pdf_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.pdf_to_image_generator:
        class: '%garant_file_preview_generator.pdf_to_image_generator.class%'
        arguments: ["@liip_imagine.filter.manager", "@garant_file_preview_generator.binary.loader.filesystem"]
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - {name: "garant_file_preview_generator.generator"}

    garant_file_preview_generator.shm.predis:
          class: Garant\FilePreviewGeneratorBundle\SharedMemory\PredisAdapter
          arguments: ["%%"]